# Use postgres/example user/password credentials
version: '3.1'

services:
  postgres-development:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'development'
      POSTGRES_USER: 'admin'
      POSTGRES_DB: 'nlw6_valoriza'
    ports:
      - '5432:5432'
    #volumes:
    #  - /home/renatogroffe/Desenvolvimento/Docker-Compose/PostgreSQL:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

  postgres-test:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'test'
      POSTGRES_USER: 'admin'
      POSTGRES_DB: 'nlw6_valoriza'
    ports:
      - '5433:5432'
    #volumes:
    #  - /home/renatogroffe/Desenvolvimento/Docker-Compose/PostgreSQL:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'thiago.suricat@gmail.com'
      PGADMIN_DEFAULT_PASSWORD: 'development'
    ports:
      - '16543:80'
    depends_on:
      - postgres-development
      - postgres-test
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
